---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the Network interface that will be used by the EC2 instances.
  This template needs to be run after the vpc stack because it needs the security groups and subnet IDS.
  Last Modified: 17.06.2024
  Author: Exec <aerioeus@gmail.com>

Metadata: {}
Mappings: {}
Conditions: {}

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/GLOBAL

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  PublicSecurityGroupID:
    Description: Security Group ID
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # create the network interfaces for all the public subnets
  ENIIdForPublicSubnet1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: !Sub ${Project}-eni1
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "PublicSubnet1"
      PrivateIpAddress: 172.16.1.1

  ENIIdForPublicSubnet2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: !Sub ${Project}-eni2
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "PublicSubnet2"
      PrivateIpAddress: 172.16.17.1

  ENIIdForPublicSubnet3:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: !Sub ${Project}-eni3
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "PublicSubnet3"
      PrivateIpAddress: 172.16.33.1

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  ENIIdForPublicSubnet1:
    Description: ID of the Network Interface associated with the public subnet 1
    Value: !Ref ENIIdForPublicSubnet1

  ENIIdForPublicSubnet2:
    Description: ID of the Network Interface associated with the public subnet 2
    Value: !Ref ENIIdForPublicSubnet2

  ENIIdForPublicSubnet3:
    Description: ID of the Network Interface associated with the public subnet 3
    Value: !Ref ENIIdForPublicSubnet3