---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the Network interface that will be used by the EC2 instances.
  This template needs to be run after the vpc_core because it needs the security groups
  and subnet IDS.

Metadata:
  ParameterLabels:
    EnvironmentName:
      default: Global parameter that indicates the deployment environment that the stack will deploy
    Owner:
      default: Team or Individual Owner
    Project:
      default: Name of the current project

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: Enter Project Name.
    Type: String
    Default: Invoicegen App

  PublicSecurityGroupID:
    Description: Security Group ID
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # create the network interfaces for all the public subnets
  ENIIdForPublicSubnet1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: invoicegenerator
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PublicSubnet1"
      PrivateIpAddress: 172.16.1.1

  ENIIdForPublicSubnet2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: invoicegenerator
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PublicSubnet2"
      PrivateIpAddress: 172.16.17.1

  ENIIdForPublicSubnet3:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Tags:
      - Key: name
        Value: invoicegenerator
      Description: Elastic Network Interface to be used by the EC2 instances
      SourceDestCheck: 'true'
      GroupSet:
        - !Ref PublicSecurityGroupID
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PublicSubnet3"
      PrivateIpAddress: 172.16.33.1

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  ENIIdForPublicSubnet1:
    Description: ID of the Network Interface associated with the public subnet 1
    Value: !Ref ENIIdForPublicSubnet1

  ENIIdForPublicSubnet2:
    Description: ID of the Network Interface associated with the public subnet 2
    Value: !Ref ENIIdForPublicSubnet2

  ENIIdForPublicSubnet3:
    Description: ID of the Network Interface associated with the public subnet 3
    Value: !Ref ENIIdForPublicSubnet3